In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [4]:
data = pd.read_excel(r'C:\Users\musku\Downloads\Association Rules\Association Rules\Online retail.xlsx',header=None)

In [5]:
data

                                                      0
0     shrimp,almonds,avocado,vegetables mix,green gr...
1                                burgers,meatballs,eggs
2                                               chutney
3                                        turkey,avocado
4     mineral water,milk,energy bar,whole wheat rice...
...                                                 ...
7496                      butter,light mayo,fresh bread
7497  burgers,frozen vegetables,eggs,french fries,ma...
7498                                            chicken
7499                                 escalope,green tea
7500    eggs,frozen smoothie,yogurt cake,low fat yogurt

[7501 rows x 1 columns]

In [6]:
data1 = data[0].str.split(',',expand=True)

In [7]:
data1.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2,chutney,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3,turkey,avocado,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
4,mineral water,milk,energy bar,whole wheat rice,green tea,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None

In [8]:
data1.shape

(7501, 20)

In [9]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7501 entries, 0 to 7500
Data columns (total 20 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       7501 non-null   object
 1   1       5747 non-null   object
 2   2       4389 non-null   object
 3   3       3345 non-null   object
 4   4       2529 non-null   object
 5   5       1864 non-null   object
 6   6       1369 non-null   object
 7   7       981 non-null    object
 8   8       654 non-null    object
 9   9       395 non-null    object
 10  10      256 non-null    object
 11  11      154 non-null    object
 12  12      87 non-null     object
 13  13      47 non-null     object
 14  14      25 non-null     object
 15  15      8 non-null      object
 16  16      4 non-null      object
 17  17      4 non-null      object
 18  18      3 non-null      object
 19  19      1 non-null      object
dtypes: object(20)
memory usage: 1.1+ MB

In [10]:
data1.describe()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
count,7501,5747,4389,3345,2529,1864,1369,981,654,395,256,154,87,47,25,8,4,4,3,1
unique,115,117,115,114,110,106,102,98,88,80,66,50,43,28,19,8,3,3,3,1
top,mineral water,mineral water,mineral water,mineral water,green tea,french fries,green tea,green tea,green tea,green tea,low fat yogurt,green tea,green tea,green tea,magazines,salmon,frozen smoothie,protein bar,spinach,olive oil
freq,577,484,375,201,153,107,96,67,57,31,22,15,8,4,3,1,2,2,1,1

In [11]:
data1.isnull().sum()

0        0
1     1754
2     3112
3     4156
4     4972
5     5637
6     6132
7     6520
8     6847
9     7106
10    7245
11    7347
12    7414
13    7454
14    7476
15    7493
16    7497
17    7497
18    7498
19    7500
dtype: int64

In [12]:
# Assuming you want to drop the columns at positions 9 through 19 (inclusive)
data1 = data1.drop(data1.columns[9:20], axis=1)

In [13]:
data1.head()

,0,1,2,3,4,5,6,7,8
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink
1,burgers,meatballs,eggs,None,None,None,None,None,None
2,chutney,None,None,None,None,None,None,None,None
3,turkey,avocado,None,None,None,None,None,None,None
4,mineral water,milk,energy bar,whole wheat rice,green tea,None,None,None,None

In [14]:
data1[data1.columns[1]].fillna(data1[data1.columns[1]].mode()[0], inplace=True)
data1[data1.columns[2]].fillna(data1[data1.columns[2]].mode()[0], inplace=True)
data1[data1.columns[3]].fillna(data1[data1.columns[3]].mode()[0], inplace=True)
data1[data1.columns[4]].fillna(data1[data1.columns[4]].mode()[0], inplace=True)
data1[data1.columns[5]].fillna(data1[data1.columns[5]].mode()[0], inplace=True)
data1[data1.columns[6]].fillna(data1[data1.columns[6]].mode()[0], inplace=True)
data1[data1.columns[7]].fillna(data1[data1.columns[7]].mode()[0], inplace=True)
data1[data1.columns[8]].fillna(data1[data1.columns[8]].mode()[0], inplace=True)

C:\Users\musku\AppData\Local\Temp\ipykernel_49488\689841466.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data1[data1.columns[1]].fillna(data1[data1.columns[1]].mode()[0], inplace=True)
C:\Users\musku\AppData\Local\Temp\ipykernel_49488\689841466.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data1[data1.columns[2]].fillna(data1[data1.columns[2]].mode()[0], inplace=True)
C:\Users\musku\AppData\Local\Temp\ipykernel_49488\689841466.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data1[data1.columns[3]].fillna(data1[data1.columns[3]].mode()[0], inplace=True)
C:\Users\musku\AppData\Local\Temp\ipykernel_49488\689841466.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data1[data1.columns[4]].fillna(data1[data1.columns[4]].mode()[0], inplace=True)
C:\Users\musku\AppData\Local\Temp\ipykernel_49488\689841466.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data1[data1.columns[5]].fillna(data1[data1.columns[5]].mode()[0], inplace=True)
C:\Users\musku\AppData\Local\Temp\ipykernel_49488\689841466.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data1[data1.columns[6]].fillna(data1[data1.columns[6]].mode()[0], inplace=True)
C:\Users\musku\AppData\Local\Temp\ipykernel_49488\689841466.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data1[data1.columns[7]].fillna(data1[data1.columns[7]].mode()[0], inplace=True)
C:\Users\musku\AppData\Local\Temp\ipykernel_49488\689841466.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data1[data1.columns[8]].fillna(data1[data1.columns[8]].mode()[0], inplace=True)

In [15]:
data1.isnull().sum()

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
dtype: int64

In [16]:
data1.duplicated().sum()

2351

In [17]:
data1.drop_duplicates(inplace=True)

In [18]:
data1.head()

,0,1,2,3,4,5,6,7,8
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink
1,burgers,meatballs,eggs,mineral water,green tea,french fries,green tea,green tea,green tea
2,chutney,mineral water,mineral water,mineral water,green tea,french fries,green tea,green tea,green tea
3,turkey,avocado,mineral water,mineral water,green tea,french fries,green tea,green tea,green tea
4,mineral water,milk,energy bar,whole wheat rice,green tea,french fries,green tea,green tea,green tea

In [19]:
data1.shape

(5150, 9)

In [21]:
!pip install mlxtend

Collecting mlxtend
  Downloading mlxtend-0.23.4-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: scipy>=1.2.1 in c:\users\musku\anaconda3\lib\site-packages (from mlxtend) (1.13.1)
Requirement already satisfied: numpy>=1.16.2 in c:\users\musku\anaconda3\lib\site-packages (from mlxtend) (1.26.4)
Requirement already satisfied: pandas>=0.24.2 in c:\users\musku\anaconda3\lib\site-packages (from mlxtend) (2.2.2)
Requirement already satisfied: scikit-learn>=1.3.1 in c:\users\musku\anaconda3\lib\site-packages (from mlxtend) (1.5.1)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\musku\anaconda3\lib\site-packages (from mlxtend) (3.9.2)
Requirement already satisfied: joblib>=0.13.2 in c:\users\musku\anaconda3\lib\site-packages (from mlxtend) (1.4.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\musku\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\musku\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\musku\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\musku\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\musku\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\musku\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\musku\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\musku\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\musku\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\musku\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2023.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\musku\anaconda3\lib\site-packages (from scikit-learn>=1.3.1->mlxtend) (3.5.0)
Requirement already satisfied: six>=1.5 in c:\users\musku\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.16.0)
Downloading mlxtend-0.23.4-py3-none-any.whl (1.4 MB)
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   --------------- ------------------------ 0.5/1.4 MB 4.2 MB/s eta 0:00:01
   ---------------------------------------- 1.4/1.4 MB 3.9 MB/s eta 0:00:00
Installing collected packages: mlxtend
Successfully installed mlxtend-0.23.4

In [22]:
#Apriori algorithm
from mlxtend.frequent_patterns import apriori,association_rules
from mlxtend.preprocessing import TransactionEncoder
#!pip install mlxtend

In [23]:
transcation = []
for i in range(data1.shape[0]):
    transcation.append([str(data1.values[i,j]) for j in range(0,data1.shape[1])])

In [24]:
te = TransactionEncoder()
te_data = te.fit(transcation).transform(transcation)

In [25]:
online_retail = pd.DataFrame(te_data,columns=te.columns_)

In [26]:
online_retail

,asparagus,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,False,True,False,False,True,False,False,False,False,False,...,False,True,False,False,True,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5145,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5146,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
5147,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5148,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5149,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False

In [27]:
freq_itemset = apriori(online_retail,min_support=0.1,use_colnames=True)

In [ ]:
freq_itemset

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

     support                                  itemsets
0   0.113981                                 (burgers)
1   0.100000                                    (cake)
2   0.201553                               (chocolate)
3   0.205437                                    (eggs)
4   0.727184                            (french fries)
5   0.129709                       (frozen vegetables)
6   0.890874                               (green tea)
7   0.135340                             (ground beef)
8   0.170485                                    (milk)
9   0.607379                           (mineral water)
10  0.119223                                (pancakes)
11  0.228932                               (spaghetti)
12  0.120388                 (french fries, chocolate)
13  0.166408                    (green tea, chocolate)
14  0.102913                (mineral water, chocolate)
15  0.128155                      (french fries, eggs)
16  0.169903                         (green tea, eggs)
17  0.105631                     (mineral water, eggs)
18  0.704854                 (french fries, green tea)
19  0.467961             (french fries, mineral water)
20  0.112039                 (french fries, spaghetti)
21  0.125243                         (green tea, milk)
22  0.545243                (green tea, mineral water)
23  0.172621                    (green tea, spaghetti)
24  0.110680                (mineral water, spaghetti)
25  0.112233      (french fries, chocolate, green tea)
26  0.120388           (french fries, eggs, green tea)
27  0.457864  (french fries, mineral water, green tea)
28  0.104078      (french fries, spaghetti, green tea)

In [28]:
rules = association_rules(freq_itemset,metric='lift',min_threshold=1)
rules.sort_values('lift',ascending=False).head(10)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(green tea),(french fries),0.890874,0.727184,0.704854,0.791194,1.088024,1.0,0.057025,1.306553,0.741370,0.771848,0.234627,0.880243
1,(french fries),(green tea),0.727184,0.890874,0.704854,0.969292,1.088024,1.0,0.057025,3.553719,0.296548,0.771848,0.718605,0.880243
2,(french fries),(mineral water),0.727184,0.607379,0.467961,0.643525,1.059512,1.0,0.026285,1.101398,0.205886,0.539996,0.092063,0.706993
3,(mineral water),(french fries),0.607379,0.727184,0.467961,0.770460,1.059512,1.0,0.026285,1.188533,0.143061,0.539996,0.158627,0.706993
4,(green tea),(mineral water),0.890874,0.607379,0.545243,0.612031,1.007660,1.0,0.004145,1.011993,0.069664,0.572127,0.011850,0.754865
5,(mineral water),(green tea),0.607379,0.890874,0.545243,0.897698,1.007660,1.0,0.004145,1.066709,0.019363,0.572127,0.062537,0.754865
6,"(chocolate, french fries)",(green tea),0.120388,0.890874,0.112233,0.932258,1.046454,1.0,0.004982,1.610911,0.050467,0.124838,0.379233,0.529119
7,(green tea),"(chocolate, french fries)",0.890874,0.120388,0.112233,0.125981,1.046454,1.0,0.004982,1.006399,0.406790,0.124838,0.006358,0.529119
8,"(eggs, french fries)",(green tea),0.128155,0.890874,0.120388,0.939394,1.054464,1.0,0.006218,1.800583,0.059243,0.133967,0.444624,0.537265
9,(green tea),"(eggs, french fries)",0.890874,0.128155,0.120388,0.135135,1.054464,1.0,0.006218,1.008070,0.473310,0.133967,0.008006,0.537265
10,"(green tea, french fries)",(mineral water),0.704854,0.607379,0.457864,0.649587,1.069492,1.0,0.029751,1.120452,0.220152,0.535909,0.107503,0.701712
11,"(green tea, mineral water)",(french fries),0.545243,0.727184,0.457864,0.839744,1.154788,1.0,0.061372,1.702369,0.294750,0.562098,0.412583,0.734692
12,"(french fries, mineral water)",(green tea),0.467961,0.890874,0.457864,0.978423,1.098274,1.0,0.040970,5.057580,0.168183,0.508190,0.802277,0.746186
13,(green tea),"(french fries, mineral water)",0.890874,0.467961,0.457864,0.513949,1.098274,1.0,0.040970,1.094616,0.819969,0.508190,0.086438,0.746186
14,(french fries),"(green tea, mineral water)",0.727184,0.545243,0.457864,0.629640,1.154788,1.0,0.061372,1.227877,0.491321,0.562098,0.185586,0.734692
15,(mineral water),"(green tea, french fries)",0.607379,0.704854,0.457864,0.753836,1.069492,1.0,0.029751,1.198981,0.165495,0.535909,0.165959,0.701712
16,"(spaghetti, french fries)",(green tea),0.112039,0.890874,0.104078,0.928943,1.042732,1.0,0.004265,1.535752,0.046152,0.115792,0.348853,0.522885
17,(green tea),"(spaghetti, french fries)",0.890874,0.112039,0.104078,0.116827,1.042732,1.0,0.004265,1.005421,0.375538,0.115792,0.005392,0.522885

In [29]:
# Experiment with different values
min_support = 0.03
min_confidence = 0.5
min_lift = 3

freq_itemset = apriori(online_retail, min_support=min_support, use_colnames=True)
rules = association_rules(freq_itemset, metric='lift', min_threshold=min_lift)
rules = rules[rules['confidence'] >= min_confidence]

In [32]:
rules

Empty DataFrame
Columns: [antecedents, consequents, antecedent support, consequent support, support, confidence, lift, representativity, leverage, conviction, zhangs_metric, jaccard, certainty, kulczynski]
Index: []

In [33]:
import joblib
joblib.dump(te, "TransactionEncoder.pkl")

['TransactionEncoder.pkl']

**1.	What is lift and why is it important in Association rules?**

Lift in association rule mining measures how much more likely two items are to be bought together than if they were purchased independently.
Identifies True Associations: A lift greater than 1 indicates a positive association, meaning the items are more likely to be purchased together. A lift of 1 suggests no association (they are independent), and a lift less than 1 implies a negative association (they are less likely to be bought together).

**2.	What is support and Confidence. How do you calculate them?**

**Support:**Support measures how frequently an itemset (a set of items) appears in the dataset. It represents the popularity of an itemset


**Confidence:**Confidence measures the strength of the association between the antecedent (the "if" part) and the consequent (the "then" part) of a rule. It indicates how likely the consequent is to be purchased when the antecedent is already in the basket.

**3.	What are some limitations or challenges of Association rules mining?**

**limitation:**

i).The Apriori algorithm requires a large amount of memory, which can be a problem when dealing with very large datasets.

ii).The Apriori algorithm may not perform well with low support values, which can lead to the generation of too many frequent itemsets.

iii).They produce boring rules, have many discovered rules, and perform poorly

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)