In [ ]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics import pairwise_distances

In [ ]:
anime_df=pd.read_csv('anime.csv')
anime_df = anime_df.sort_values(by ='anime_id').reset_index(drop = True)
anime_df

,anime_id,name,genre,type,episodes,rating,members
0,1,Cowboy Bebop,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,26,8.82,486824
1,5,Cowboy Bebop: Tengoku no Tobira,"Action, Drama, Mystery, Sci-Fi, Space",Movie,1,8.40,137636
2,6,Trigun,"Action, Comedy, Sci-Fi",TV,26,8.32,283069
3,7,Witch Hunter Robin,"Action, Drama, Magic, Mystery, Police, Superna...",TV,26,7.36,64905
4,8,Beet the Vandel Buster,"Adventure, Fantasy, Shounen, Supernatural",TV,52,7.06,9848
...,...,...,...,...,...,...,...
12289,34514,Pokemon Generations,"Action, Adventure, Fantasy, Game, Kids",ONA,18,7.21,295
12290,34519,Mobile Suit Gakuen: G-Reco Koushien,Comedy,Special,9,5.67,94
12291,34522,"Wake Up, Girls! Shin Shou","Drama, Music",TV,Unknown,NaN,381
12292,34525,Centaur no Nayami,"Comedy, Fantasy, Slice of Life, Supernatural",TV,Unknown,NaN,108
12293,34527,Gou-chan. Moko to Chinjuu no Mori no Nakama-tachi,"Adventure, Kids",Movie,1,NaN,5

In [ ]:
anime_df.head()

,anime_id,name,genre,type,episodes,rating,members
0,1,Cowboy Bebop,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",TV,26,8.82,486824
1,5,Cowboy Bebop: Tengoku no Tobira,"Action, Drama, Mystery, Sci-Fi, Space",Movie,1,8.40,137636
2,6,Trigun,"Action, Comedy, Sci-Fi",TV,26,8.32,283069
3,7,Witch Hunter Robin,"Action, Drama, Magic, Mystery, Police, Superna...",TV,26,7.36,64905
4,8,Beet the Vandel Buster,"Adventure, Fantasy, Shounen, Supernatural",TV,52,7.06,9848

In [ ]:
anime_df.tail()

,anime_id,name,genre,type,episodes,rating,members
12289,34514,Pokemon Generations,"Action, Adventure, Fantasy, Game, Kids",ONA,18,7.21,295
12290,34519,Mobile Suit Gakuen: G-Reco Koushien,Comedy,Special,9,5.67,94
12291,34522,"Wake Up, Girls! Shin Shou","Drama, Music",TV,Unknown,NaN,381
12292,34525,Centaur no Nayami,"Comedy, Fantasy, Slice of Life, Supernatural",TV,Unknown,NaN,108
12293,34527,Gou-chan. Moko to Chinjuu no Mori no Nakama-tachi,"Adventure, Kids",Movie,1,NaN,5

In [ ]:
anime_df.shape

(12294, 7)

In [ ]:
anime_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   anime_id  12294 non-null  int64
 1   name      12294 non-null  object
 2   genre     12232 non-null  object
 3   type      12269 non-null  object
 4   episodes  12294 non-null  object
 5   rating    12064 non-null  float64
 6   members   12294 non-null  int64
dtypes: float64(1), int64(2), object(4)
memory usage: 672.5+ KB

In [ ]:
anime_df.describe()

           anime_id        rating       members
count  12294.000000  12064.000000  1.229400e+04
mean   14058.221653      6.473902  1.807134e+04
std    11455.294701      1.026746  5.482068e+04
min        1.000000      1.670000  5.000000e+00
25%     3484.250000      5.880000  2.250000e+02
50%    10260.500000      6.570000  1.550000e+03
75%    24794.500000      7.180000  9.437000e+03
max    34527.000000     10.000000  1.013917e+06

In [ ]:
#checking for missing values
anime_df.isnull().sum()

anime_id      0
name          0
genre        62
type         25
episodes      0
rating      230
members       0
dtype: int64

In [ ]:
#handling missing values
anime_df['genre'].fillna(anime_df['genre'].mode()[0], inplace=True)
anime_df['type'].fillna(anime_df['type'].mode()[0], inplace=True)
anime_df['rating'].fillna(anime_df['rating'].mode()[0], inplace=True)

In [ ]:
anime_df.isnull().sum()

anime_id    0
name        0
genre       0
type        0
episodes    0
rating      0
members     0
dtype: int64

In [ ]:
anime_df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
12289    False
12290    False
12291    False
12292    False
12293    False
Length: 12294, dtype: bool

In [ ]:
anime_df.duplicated().sum()

0

In [ ]:
#number of unique users in the dataset
len(anime_df.anime_id	.unique())

12294

In [ ]:
len(anime_df.genre.unique())

3264

In [ ]:
user_anime_df = anime_df.pivot(index='anime_id',
                                 columns='genre',
                                 values='rating').reset_index()

In [ ]:
user_anime_df

genre,anime_id,Action,"Action, Adventure","Action, Adventure, Cars, Comedy, Sci-Fi, Shounen","Action, Adventure, Cars, Mecha, Sci-Fi, Shounen, Sports","Action, Adventure, Cars, Sci-Fi","Action, Adventure, Comedy","Action, Adventure, Comedy, Demons, Drama, Ecchi, Horror, Mystery, Romance, Sci-Fi","Action, Adventure, Comedy, Demons, Fantasy, Magic","Action, Adventure, Comedy, Demons, Fantasy, Magic, Romance, Shounen, Supernatural",...,Slice of Life,"Slice of Life, Space","Slice of Life, Supernatural",Space,Sports,"Super Power, Supernatural, Vampire",Supernatural,Thriller,Vampire,Yaoi
0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12289,34514,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12290,34519,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12291,34522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12292,34525,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12293,34527,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
user_anime_df.index = anime_df.anime_id.unique()

In [ ]:
user_anime_df

genre,anime_id,Action,"Action, Adventure","Action, Adventure, Cars, Comedy, Sci-Fi, Shounen","Action, Adventure, Cars, Mecha, Sci-Fi, Shounen, Sports","Action, Adventure, Cars, Sci-Fi","Action, Adventure, Comedy","Action, Adventure, Comedy, Demons, Drama, Ecchi, Horror, Mystery, Romance, Sci-Fi","Action, Adventure, Comedy, Demons, Fantasy, Magic","Action, Adventure, Comedy, Demons, Fantasy, Magic, Romance, Shounen, Supernatural",...,Slice of Life,"Slice of Life, Space","Slice of Life, Supernatural",Space,Sports,"Super Power, Supernatural, Vampire",Supernatural,Thriller,Vampire,Yaoi
1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34514,34514,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34519,34519,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34522,34522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34525,34525,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34527,34527,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Impute those NaNs with 0 values
user_anime_df.fillna(0, inplace=True)

In [ ]:
user_anime_df

genre,anime_id,Action,"Action, Adventure","Action, Adventure, Cars, Comedy, Sci-Fi, Shounen","Action, Adventure, Cars, Mecha, Sci-Fi, Shounen, Sports","Action, Adventure, Cars, Sci-Fi","Action, Adventure, Comedy","Action, Adventure, Comedy, Demons, Drama, Ecchi, Horror, Mystery, Romance, Sci-Fi","Action, Adventure, Comedy, Demons, Fantasy, Magic","Action, Adventure, Comedy, Demons, Fantasy, Magic, Romance, Shounen, Supernatural",...,Slice of Life,"Slice of Life, Space","Slice of Life, Supernatural",Space,Sports,"Super Power, Supernatural, Vampire",Supernatural,Thriller,Vampire,Yaoi
1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34514,34514,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34519,34519,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34522,34522,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34525,34525,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34527,34527,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
user_anime_df.head()

genre,anime_id,Action,"Action, Adventure","Action, Adventure, Cars, Comedy, Sci-Fi, Shounen","Action, Adventure, Cars, Mecha, Sci-Fi, Shounen, Sports","Action, Adventure, Cars, Sci-Fi","Action, Adventure, Comedy","Action, Adventure, Comedy, Demons, Drama, Ecchi, Horror, Mystery, Romance, Sci-Fi","Action, Adventure, Comedy, Demons, Fantasy, Magic","Action, Adventure, Comedy, Demons, Fantasy, Magic, Romance, Shounen, Supernatural",...,Slice of Life,"Slice of Life, Space","Slice of Life, Supernatural",Space,Sports,"Super Power, Supernatural, Vampire",Supernatural,Thriller,Vampire,Yaoi
1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
#Calculating Cosine Similarity between Users
from sklearn.metrics import pairwise_distances

In [ ]:
anime_sim = 1 - pairwise_distances( user_anime_df.values,metric='cosine')

In [ ]:
anime_sim

array([[1.        , 0.05762219, 0.06589538, ..., 0.11265691, 0.11265691,
        0.11265691],
       [0.05762219, 1.        , 0.29917761, ..., 0.51148385, 0.51148385,
        0.51148385],
       [0.06589538, 0.29917761, 1.        , ..., 0.5849209 , 0.5849209 ,
        0.5849209 ],
       ...,
       [0.11265691, 0.51148385, 0.5849209 , ..., 1.        , 0.99999997,
        0.99999997],
       [0.11265691, 0.51148385, 0.5849209 , ..., 0.99999997, 1.        ,
        0.99999997],
       [0.11265691, 0.51148385, 0.5849209 , ..., 0.99999997, 0.99999997,
        1.        ]])

In [ ]:
#Store the results in a dataframe
anime_sim_df = pd.DataFrame(anime_sim)

In [ ]:
anime_sim_df

,0,1,2,3,4,5,6,7,8,9,...,12284,12285,12286,12287,12288,12289,12290,12291,12292,12293
0,1.000000,0.057622,0.065895,0.077639,0.084468,0.099183,0.100308,0.102530,0.102434,0.102389,...,0.112657,0.112657,0.112657,0.112657,0.112657,0.112657,0.112657,0.112657,0.112657,0.112657
1,0.057622,1.000000,0.299178,0.352496,0.383502,0.450308,0.455417,0.465506,0.465070,0.464864,...,0.511484,0.511484,0.511484,0.511484,0.511484,0.511484,0.511484,0.511484,0.511484,0.511484
2,0.065895,0.299178,1.000000,0.403106,0.438564,0.514962,0.520805,0.532342,0.531843,0.531607,...,0.584921,0.584921,0.585062,0.584921,0.584921,0.584921,0.584921,0.584921,0.584921,0.584921
3,0.077639,0.352496,0.403106,1.000000,0.516723,0.606736,0.613620,0.627214,0.626626,0.626348,...,0.689163,0.689163,0.689163,0.689163,0.689163,0.689163,0.689163,0.689163,0.689163,0.689163
4,0.084468,0.383502,0.438564,0.516723,1.000000,0.660106,0.667595,0.682385,0.681745,0.681443,...,0.749783,0.749783,0.749783,0.749783,0.749783,0.749783,0.749783,0.749783,0.749783,0.749783
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12289,0.112657,0.511484,0.584921,0.689163,0.749783,0.880396,0.890385,0.910110,0.909256,0.908853,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
12290,0.112657,0.511484,0.584921,0.689163,0.749783,0.880396,0.890385,0.910110,0.909256,0.908853,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
12291,0.112657,0.511484,0.584921,0.689163,0.749783,0.880396,0.890385,0.910110,0.909256,0.908853,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
12292,0.112657,0.511484,0.584921,0.689163,0.749783,0.880396,0.890385,0.910110,0.909256,0.908853,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
12293,0.112657,0.511484,0.584921,0.689163,0.749783,0.880396,0.890385,0.910110,0.909256,0.908853,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
#Set the index and column names to user ids
anime_sim_df .index = anime_df.anime_id.unique()
anime_sim_df .columns = anime_df.anime_id.unique()

In [ ]:
anime_sim_df.iloc[0:10, 0:10]

,1,5,6,7,8,15,16,17,18,19
1,1.000000,0.057622,0.065895,0.077639,0.084468,0.099183,0.100308,0.102530,0.102434,0.102389
5,0.057622,1.000000,0.299178,0.352496,0.383502,0.450308,0.455417,0.465506,0.465070,0.464864
6,0.065895,0.299178,1.000000,0.403106,0.438564,0.514962,0.520805,0.532342,0.531843,0.531607
7,0.077639,0.352496,0.403106,1.000000,0.516723,0.606736,0.613620,0.627214,0.626626,0.626348
8,0.084468,0.383502,0.438564,0.516723,1.000000,0.660106,0.667595,0.682385,0.681745,0.681443
15,0.099183,0.450308,0.514962,0.606736,0.660106,1.000000,0.783891,0.801257,0.800505,0.800151
16,0.100308,0.455417,0.520805,0.613620,0.667595,0.783891,1.000000,0.810348,0.809588,0.809229
17,0.102530,0.465506,0.532342,0.627214,0.682385,0.801257,0.810348,1.000000,0.827523,0.827156
18,0.102434,0.465070,0.531843,0.626626,0.681745,0.800505,0.809588,0.827523,1.000000,0.826380
19,0.102389,0.464864,0.531607,0.626348,0.681443,0.800151,0.809229,0.827156,0.826380,1.000000

In [ ]:
np.fill_diagonal(anime_sim, 0)
anime_sim_df.iloc[0:10, 0:10]

,1,5,6,7,8,15,16,17,18,19
1,0.000000,0.057622,0.065895,0.077639,0.084468,0.099183,0.100308,0.102530,0.102434,0.102389
5,0.057622,0.000000,0.299178,0.352496,0.383502,0.450308,0.455417,0.465506,0.465070,0.464864
6,0.065895,0.299178,0.000000,0.403106,0.438564,0.514962,0.520805,0.532342,0.531843,0.531607
7,0.077639,0.352496,0.403106,0.000000,0.516723,0.606736,0.613620,0.627214,0.626626,0.626348
8,0.084468,0.383502,0.438564,0.516723,0.000000,0.660106,0.667595,0.682385,0.681745,0.681443
15,0.099183,0.450308,0.514962,0.606736,0.660106,0.000000,0.783891,0.801257,0.800505,0.800151
16,0.100308,0.455417,0.520805,0.613620,0.667595,0.783891,0.000000,0.810348,0.809588,0.809229
17,0.102530,0.465506,0.532342,0.627214,0.682385,0.801257,0.810348,0.000000,0.827523,0.827156
18,0.102434,0.465070,0.531843,0.626626,0.681745,0.800505,0.809588,0.827523,0.000000,0.826380
19,0.102389,0.464864,0.531607,0.626348,0.681443,0.800151,0.809229,0.827156,0.826380,0.000000

In [ ]:
#Most Similar Users
anime_sim_df.idxmax(axis=1)[0:5]

1     4037
5    34476
6     2097
7    34476
8      613
dtype: int64

In [ ]:
anime_df[(anime_df['anime_id']==6) | (anime_df['anime_id']==2097)]

,anime_id,name,genre,type,episodes,rating,members
2,6,Trigun,"Action, Comedy, Sci-Fi",TV,26,8.32,283069
1917,2097,Tokumu Sentai Shinesman,"Action, Comedy, Sci-Fi",OVA,2,7.07,1588

In [ ]:
name_1=anime_df[anime_df['anime_id']==6]
name_1

   anime_id    name                   genre type episodes  rating  members
2         6  Trigun  Action, Comedy, Sci-Fi   TV       26    8.32   283069

In [ ]:
name_2=anime_df[anime_df['anime_id']==2097]
name_2

,anime_id,name,genre,type,episodes,rating,members
1917,2097,Tokumu Sentai Shinesman,"Action, Comedy, Sci-Fi",OVA,2,7.07,1588

In [ ]:
pd.merge(name_1, name_2, on='genre', how='inner')

,anime_id_x,name_x,genre,type_x,episodes_x,rating_x,members_x,anime_id_y,name_y,type_y,episodes_y,rating_y,members_y
0,6,Trigun,"Action, Comedy, Sci-Fi",TV,26,8.32,283069,2097,Tokumu Sentai Shinesman,OVA,2,7.07,1588

In [ ]:
Action_Adventure_rating = user_anime_df['Action, Adventure']
print(Action_Adventure_rating)

1        0.0
5        0.0
6        0.0
7        0.0
8        0.0
        ...
34514    0.0
34519    0.0
34522    0.0
34525    0.0
34527    0.0
Name: Action, Adventure, Length: 12294, dtype: float64

In [ ]:
#Finding the correlation with different movies
Action_Adventure_rating= user_anime_df.corrwith(Action_Adventure_rating)

In [ ]:
Action_Adventure_rating.head()

genre
anime_id                                                  -0.004996
Action                                                    -0.002246
Action, Adventure                                          1.000000
Action, Adventure, Cars, Comedy, Sci-Fi, Shounen          -0.000440
Action, Adventure, Cars, Mecha, Sci-Fi, Shounen, Sports   -0.000311
dtype: float64

In [ ]:
corr_Action_Adventure = pd.DataFrame(Action_Adventure_rating, columns=['Correlation'])
corr_Action_Adventure .dropna(inplace=True)
corr_Action_Adventure .head()

                                                    Correlation
genre
anime_id                                              -0.004996
Action                                                -0.002246
Action, Adventure                                      1.000000
Action, Adventure, Cars, Comedy, Sci-Fi, Shounen      -0.000440
Action, Adventure, Cars, Mecha, Sci-Fi, Shounen...    -0.000311

In [ ]:
corr_Action_Adventure[corr_Action_Adventure['Correlation'] > 0].sort_values(by='Correlation', ascending=False)

                   Correlation
genre
Action, Adventure          1.0

In [ ]:
X = anime_df.drop('rating', axis=1)
y = anime_df['genre']

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [ ]:
anime_df['movie_encoded'] = le.fit_transform(anime_df['genre'])

In [ ]:
# Now recreate X and y with the encoded column
X = anime_df.drop(['genre'], axis=1)
y = anime_df['rating']

In [ ]:
# use a Linear Regression model:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

In [ ]:
# Perform train-test split (if not already done)
from sklearn.model_selection import train_test_split

# Make sure X and y are defined in this scope
X = anime_df.drop(['genre', 'name', 'rating'], axis=1)  # Assuming anime_df is available. Dropping the 'name' column which likely contains strings and the target column 'rating'
y = anime_df['rating']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

# Handle non-numeric columns (example using one-hot encoding)
X_train = pd.get_dummies(X_train)
X_test = pd.get_dummies(X_test) # Apply same transformation to test data

# Align columns in training and test sets
# Get missing columns in the training set
missing_cols_train = set(X_test.columns) - set(X_train.columns)
# Add a missing column in test set with default value equal to 0
for c in missing_cols_train:
    X_train[c] = 0
# Get missing columns in the testing set
missing_cols_test = set(X_train.columns) - set(X_test.columns)
# Add a missing column in test set with default value equal to 0
for c in missing_cols_test:
    X_test[c] = 0

# Ensure the order of column in the test set is in the same order than in train set
X_test = X_test[X_train.columns]

model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import mean_squared_error, r2_score

In [ ]:
# Calculate Mean Squared Error
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

# Calculate R-squared score
r2 = r2_score(y_test, y_pred)
print("R-squared:", r2)

Mean Squared Error: 184002313.7043268
R-squared: -186386584.52237236

**Interview Questions:**

**1.Can you explain the difference between user-based and item-based collaborative filtering?**

user-based collaborative filtering:

Collaborative filtering is a popular technique used in recommender systems to predict a user's preferences for items

item-based collaborative filtering:

Recommends items based on their similarity to other items the user has liked.Determines how similar items are to each other based on user ratings or interactions.

**2.What is collaborative filtering, and how does it work?**

Collaborative filtering is a powerful technique used in recommender systems to predict a user's preferences for items like movies, products, music based on the tastes of similar users or the characteristics of similar items.

How it works:

Data Collection: Gather a dataset of user-item interactions, such as ratings or purchases.
Similarity Calculation: Determine the similarity between users or items.

Recommendation Generation: Use the calculated similarities to predict which items a user might like.